name: hojozaty
description: An app to help with restaurants, cafes and hotels reservations
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_inner_drawer: ^0.5.5
  http: ^0.12.0+4
  pull_to_refresh: ^1.5.8
  shared_preferences: ^0.5.4+8
  fancy_bottom_navigation:
  rounded_floating_app_bar: 0.1.0
  flutter_swiper:
  flutter_multi_carousel: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/main-logo.png
    - assets/loading.gif
    - assets/hotels.jpg
    - assets/restaurants.jpg
    - assets/cafes.jpg
    - assets/terwada.jpg